# Generated by Django 3.2.7 on 2021-09-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20210915_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterModelTable(
            name='image',
            table='gallery',
        ),
    ]
